kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy
  annotations:
    description: cube-node
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cube-node
  template:
    metadata:
      name: cube-node
      labels:
        env: dev
        name: cube-node
    spec:
      containers:
        - name: cube-node
          image: "cube-node"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: cube-node
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: cube-node
  type: NodePort
